### PR TITLE
Add "No description for this constant" message

### PR DESCRIPTION
**Pull request by Mickeon**
Required for https://github.com/godotengine/godot/pull/85836

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Well I was a bit fast, seems like we might need the same for enums too as per https://github.com/godotengine/godot/pull/85836#issuecomment-1843066523.

But let's see if that PR actually get finalized.

**Comment by Mickeon** [comment]
If it's not done in a few days I could revive it and give credit

**Comment by akien-mga** [comment]
Since it hasn't been updated in a month and was never updated by the OP after being opened, I'd suggest being proactive and doing it now already.

**Comment by Mickeon** [comment]
https://github.com/godotengine/godot/pull/87259

**Pull request merged**
